### ISSUE TITLE
Add Montserrat Font

### ISSUE THREAD

**Issue by estebanborai** [learnFE/website#6]
Add the **Montserrat** font as the default font.
You can get the font from this link: https://fonts.google.com/specimen/Montserrat

**Comment by Leeoku** [comment]
completed in my version

**Comment by estebanborai** [comment]
@Leeoku Nice! Can you make a PR so I add it to the `master`?

**Comment by Leeoku** [comment]
it's already in my other commit? I need to do another?

**Comment by estebanborai** [comment]
@Leeoku its done with your PR. Closing the issue as #14 resolves the issue.
